In [170]:
import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns 
import xgboost as xgb

FOR THIS MODEL I WILL TRY TO LEARN ENESAMBLES AND USE A ENSAMBLE MODEL
THE MODEL WILL CONTAIN ,FOR NOW:-
XGBOOST,KNN,RANDOM FOREST, SIMPLE DENSE NEURAL NETWORK,LOGISTIC REGRESSION,

In [171]:
#load data
data=pd.read_csv(r'C:\Users\defaultuser0.LAPTOP-LRB3T941\Documents\Tensorflow\KAGGLE COMPETITION\spaceship-titanic\train.csv')
data.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [172]:
# I'LL DO THIS IN PORE
#sns.heatmap(pd.get_dummies(data,drop_first=True))
#data.head()
y=data['Transported']
X=data.drop('Transported',axis=1)
X=X.drop('Name',axis=1)
X.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0

In [173]:
data.isnull().sum()
data.shape
from sklearn.pipeline import FeatureUnion
y=pd.get_dummies(y,drop_first=True)
y.head()

   True
0     0
1     1
2     0
3     0
4     1

XGBOOST

In [174]:
def dick(x):
    return x.apply(lambda x:x.to_dict())

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction import DictVectorizer
from sklearn.model_selection import cross_val_score
from sklearn_pandas import DataFrameMapper
from sklearn.impute import SimpleImputer
import sklearn_pandas
catagorical_columns=X.columns[X.dtypes==object].to_list()
numeric_columns=X.columns[X.dtypes!=object].to_list()
#print(numeric_columns)

numeric_mapper=DataFrameMapper([([numeric_column],SimpleImputer(strategy="median")) for numeric_column in numeric_columns ],input_df=True,df_out=True)
catagoric_mapper=DataFrameMapper([([catagory],SimpleImputer(strategy='most_frequent')) for catagory in catagorical_columns],input_df=True,df_out=True)
print(type(catagoric_mapper))
union=FeatureUnion( [('hello',numeric_mapper),('mello',catagoric_mapper)])
#union=pd.DataFrame(union)
print((union))
#pipeline=Pipeline([('unio',union),('vect',DictVectorizer(sort=False)),('difrck',xgb.XGBClassifier )   ])
pipeline=Pipeline([('unio',union),('vect',DictVectorizer(sort=False,dtype=object)),('difrck',xgb.XGBClassifier)])


#cross_val_scores=cross_val_score(pipeline,X,y,scoring='accuracy',cv=3)

In [175]:
X_test=pd.read_csv(r'C:\Users\defaultuser0.LAPTOP-LRB3T941\Documents\Tensorflow\KAGGLE COMPETITION\spaceship-titanic\test.csv')
X_test=X_test.drop('Name',axis=1)

In [153]:
print(X_test.columns , '\n' , X.columns)

Index(['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age',
       'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck'],
      dtype='object')
 Index(['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age',
       'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck'],
      dtype='object')

In [154]:
imput=SimpleImputer(strategy='most_frequent')
imput_v2=SimpleImputer(strategy='median')
catagorical_value=X[X.columns[X.dtypes==object]]   
num_value=X[X.columns[X.dtypes!=object]]
TEST_catagorical_value=X_test[X_test.columns[X_test.dtypes==object]]   
TEST_num_value=X_test[X_test.columns[X_test.dtypes!=object]]

catagorical_value=imput.fit_transform(catagorical_value)
TEST_catagorical_value=imput.transform(TEST_catagorical_value)
num_value=imput_v2.fit_transform(num_value)
TEST_num_value=imput_v2.transform(TEST_num_value)
#X_train=pd.concat([catagorical_value,num_value],axis=1)
#print(catagorical_value)
#=imput.fit_transform()
X_train=np.append(catagorical_value,num_value,axis=1)
X_test_final=np.append(TEST_catagorical_value,TEST_num_value)

In [183]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.model_selection import cross_val_score
x=pd.get_dummies(X,drop_first=True)
#df=dick.fit_transform(df)

#print(X_test_final[:10])
model=xgb.XGBClassifier()
model.fit(x,y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [188]:

x_TEST=pd.get_dummies(X_test,drop_first=True)
#yy=model.predict(x_TEST)
x_TEST.head()

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,PassengerId_0018_01,PassengerId_0019_01,PassengerId_0021_01,PassengerId_0023_01,...,Cabin_G/996/P,Cabin_G/997/P,Cabin_G/997/S,Cabin_T/0/S,Cabin_T/1/S,Cabin_T/3/S,Cabin_T/4/P,Destination_PSO J318.5-22,Destination_TRAPPIST-1e,VIP_True
0,27.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,19.0,0.0,9.0,0.0,2823.0,0.0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,31.0,0.0,0.0,0.0,0.0,0.0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,38.0,0.0,6652.0,0.0,181.0,585.0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
4,20.0,10.0,0.0,635.0,0.0,0.0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0

In [ ]:
from sklearn.feature_extraction import DictVectorizer
dick=DictVectorizer(dtype=object,sort=False)

lst = X_train.tolist()

#suck=dick.fit_transform((X_train))
print(lst)
suck=dick.fit_transform(lst)
#cuck=dick.transform(pd.DataFrame(X_test_final))